### ISSUE TITLE
Why not use gpu?

### ISSUE THREAD

**Issue by ghost** [lixin4ever/HAST#3]
hi @lixin4ever
thank you for your job. 
Is it faster to use gpu  for inference?
 How can I use the GPU?  set  dynet_config.set(gpu= true  ?

**Comment by lixin4ever** [comment]
Sorry for the late reply.

1. The reason why we use cpu is that we want to report deterministic results.

2. Yes, using gpu will make the program running faster but the results may not be deterministic.

3. For using gpu, you should reinstall dynet and specify the gpu backend (i.e., cuda) and the path of CUDNN (please refer to https://dynet.readthedocs.io/en/latest/python.html#installing-a-cutting-edge-and-or-gpu-version)

**Comment by ghost** [comment]
@lixin4ever  
Thank you for your guidance
