### ISSUE TITLE
Run on GPU

### ISSUE THREAD

**Issue by dimtsintzou** [lixin4ever/HAST#4]
Hi did you managed to use gpu on this?

**Comment by lixin4ever** [comment]
First of all, you should follow the [tutorial](https://dynet.readthedocs.io/en/latest/python.html#installing-a-cutting-edge-and-or-gpu-version) to install a GPU version of DyNet.

Then, you need to explicitly declare the GPU as the default device type before the import of dynet, as done in the following code snippet:  

```
import dynet_config
# Declare GPU as the default device type
dynet_config.set_gpu()
# Set some parameters manualy
dynet_config.set(mem=4,random_seed=9)
# Initialize dynet import using above configuration in the current scope
import dynet
```
